### ISSUE TITLE
netcdf

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#12]
Hi Lion,

I got a friend asking me about the asdf. But unfortunately, he wants the netcdf...

I think hdf5 is thought to be better than netcdf. But do we have plans to provide netcdf in the future?

**Comment by krischer** [comment]
There are no plans to support netcdf4. It would be possible but its really kind of pointless for the `ASDF` format and we do gain a lot by sticking to a single container format.

netcdf4 is based on top of HDF5 so it is "just" another layer sitting on top of. It is indeed very useful for high-dimensional gridded data like they are common for example in climate science, e.g. a global 4 dimensional wind field but that is mainly due to the available tools.

We would gain nothing from using netcdf4; we would actually lose some feature like references which the netcdf data model AFAIK cannot accomodate. Also one less software layer means one less point of failure and as parallel I/O is still very tricky across different machines (as I'm sure you've noticed ;-) ) that is actually a pretty big advantage.

**Comment by wjlei1990** [comment]
OK. I am going to tell him.

I think rather than providing the netcdf, it is better to provide multiple language interface for the potential users, including the fortran, C/C++, python.

We should make it simple, clean and easy to learn. So people can modify the I/O in their code to accommodate asdf.

**Comment by krischer** [comment]
> I think rather than providing the netcdf, it is better to provide multiple language interface for the potential users, including the fortran, C/C++, python.
> 
> We should make it simple, clean and easy to learn. So people can modify the I/O in their code to accommodate asdf.

:+1: This is also exactly what we have been doing :-)
