### ISSUE TITLE
tag strings starting with numbers

### ISSUE THREAD

**Issue by dyna-ingv** [SeismicData/pyasdf#22]
Hi Lion,

perhaps we are missing something in the docs, or maybe something is not working properly:

pyasdf allows to tag waveforms (or any other data) with strings starting with numbers, but trying to access previously tagged data results in "invalid syntax" exception.

moreover, network names starting with numbers result in the same behaviour (FDSN specifications allow numbers in net codes, and some actual networks already use this syntax).

PS we are also allowed to insert special chars in tag strings... should it be forbidden?

sample sessions below (using latest pyasdf from git repository)

a) tag string starting with numbers

```
In [1]: import pyasdf

In [2]: ds = pyasdf.ASDFDataSet("test.h5", compression="gzip-3")

In [3]: ds.add_waveforms('input.mseed', tag='00_XX', event_id='test')

In [4]: ds.waveforms.NZ_RTZ.00_XX
  File "<ipython-input-4-124329b5b6a4>", line 1
    ds.waveforms.NZ_RTZ.00_XX
                         ^
SyntaxError: invalid syntax
```

b) tag string starting with letters

```
In [5]: ds.add_waveforms('input.mseed', tag='YY_00', event_id='test')

In [6]: ds.waveforms.NZ_RTZ.YY_00
Out[6]: 
1 Trace(s) in Stream:
NZ.RTZ.20.HNE | 2016-02-01T19:02:03.000000Z - 2016-02-01T19:05:23.995000Z | 200.0 Hz, 40200 samples
```

c) tag string containing special chars (....is this allowed?)

```
In [9]: ds.add_waveforms('input.mseed', tag='YY_0%%%%0', event_id='test')

In [10]: ds.waveforms.NZ_RTZ.YY_0%%%%0
  File "<ipython-input-10-1e37cee81f48>", line 1
    ds.waveforms.NZ_RTZ.YY_0%%%%0
                             ^
SyntaxError: invalid syntax
```

d) network names starting with numbers result in the same error!

```
In [4]: ds.waveforms.11_RTZ
  File "<ipython-input-4-20ad8374b5b6>", line 1
    ds.waveforms.11_RTZ
                  ^
SyntaxError: invalid syntax
```

**Comment by krischer** [comment]
Heyhey!

That is actually not allowed by the definition. See here: http://asdf.readthedocs.org/en/latest/waveforms.html#waveform-traces

It specifies that the tag part has to satisfy the following regular expression:

`[a-z_0-9]+`

So lowercase letter, numbers and an underscore are allowed. `pyasdf` currently does not check that. I'll add that at once! Before I do that: Do you think that is a reasonable limitation? I used lowercase letters to effectively gain case-insensitive tags.

The syntax error you have is due to a limitation of the Python syntax (attributes have to start with a letter). You can still retrieve it by using key access instead of attribute access, e.g.

```python
ds.waveforms.NZ_RTZ["00_XX"]
ds.waveforms.NZ_RTZ["YY_0%%%%0"]    # You might have to escape the percent signs...
```

BTW: The validator catches all these problems: https://github.com/SeismicData/asdf_validate

```bash
$ asdf-validate seismo.h5
```
It is pretty slow but it does a very thorough job of making sure a file is a valid ASDF file.

**Comment by dyna-ingv** [comment]
ok, mmmh

...probably the safest way to access all data with pyasdf is to escape always,
as network names can actually start with numbers too  (see previous post edit).

thank you!

**Comment by krischer** [comment]
> ...probably the safest way to access all data with pyasdf is to escape always,
> as network names can actually start with numbers too (see previous post edit).

True. There is unfortunately nothing I can do in that regard as I am bound to Python's syntax.

**Comment by dyna-ingv** [comment]
problem solved: "always escape" :)

**Comment by krischer** [comment]
If you checkout the latest `pyadsf` version it is no longer possible to create waveforms with invalid tags.

**Comment by dyna-ingv** [comment]
uppercase tags are explicitly forbidden?
ok for us :)

**Comment by krischer** [comment]
Yes. The reasoning is that I think it would be confusing to have `Example` and `example` as two separate tags. Only allowing lower case force case-insensitivity.

All symbols except underscores are forbidden as well.
