### ISSUE TITLE
storing complex valued data

### ISSUE THREAD

**Issue by rvbelefonte** [SeismicData/pyasdf#33]
Adding a waveform with complex valued data (e.g. spectra) raises a TypeError:

`TypeError: The trace's dtype ('complex128') is not allowed inside ASDF. Allowed are little and big endian 4 and 8 byte signed integers and floating point numbers.`
#
A work around is to split the real and imaginary parts into separate tags, but this seems kludgy.  Is this a design decision, or am I missing something?

**Comment by krischer** [comment]
That's a design decision but if you disagree we are very open for discussion.

The waveforms are really intended to store seismic waveforms as time series data. Anything else is supposed to be stored in the auxiliary data group. The reasoning is that most other things just don't have an established standard on how they should be stored and also what meta information is really required and the auxiliary data gives flexibility to store anything. This is also described in the paper in a bit more detail: http://dx.doi.org/10.1093/gji/ggw319

```python
>>> import numpy as np
>>> from pyasdf import ASDFDataSet
>>> ds = ASDFDataSet("temp.h5")
>>> ds.add_auxiliary_data(data=np.empty(1000, dtype=np.complex128),
...                       data_type="Spectra", path="name_for_it",
...                       parameters={"df": 0.01})

# Reading it again:

>>> ds.auxiliary_data.Spectra.name_for_it
Auxiliary Data of Type 'Spectra'
	Path: 'name_for_it'
	Data shape: '(1000,)', dtype: 'complex128'
	Parameters:
		df: 0.01
```

`data_type` is supposed to be the type of the data in a single word, and `parameters` are arbitrary extra arguments useful to store meta information. Note that the paths can be arbitrarily nested, e.g. `path="some/deep/path"` allowing for complex hierarchies.

**Comment by rvbelefonte** [comment]
Thanks Lion.  I agree with your aux data approach and see the logic.  I should have started by saying thanks for the work on ASDF and this great tool!

I'd like to calculate and store complex spectra for segments.  My approach now is to chunk up the data into single days and store an nsegment x npts complex array for each day under `path=<year>/<julday>/<sta_chan>`.  Is there a more efficient approach?

Nathan

**Comment by krischer** [comment]
Hi Nathan,

thanks :-) The next step is to get the community to try it out and hopefully adopt it but it seems to be going quite well.

`path=<year>/<julday>/<sta_chan>` is perfectly fine. Nesting helps when there are a lot of datasets but its not strictly necessary. HDF5 has no limit on the number of datasets per group and I guess it gets a bit slower once a certain number is reached but that is probably a very high number.

One thing to keep in mind: if you use e.g. `path="2009/135/BW_ALTM"` you can no longer use the dot accessors in `pyasdf`, e.g.

`ds.auxiliary_data.Spectra.2009.135.BW_ALTM`

does not work. This is a limitation of Python as attributes cannot start with a number. You have to do

`ds.auxiliary_data.Spectra["2009"]["135"]["BW_ALTM"]`

which does exactly the same but tab completion in IPython no longer works. Otherwise it has no further consequences.

You could use `path="Y2009/J135/BW_ALTM"` and tab completion/dot access works which might be a bit more convenient.

Cheers!

Lion
