### ISSUE TITLE
Parallel processing request for comment

### ISSUE THREAD

**Issue by rmodrak** [SeismicData/pyasdf#36]
The parallel processing capabilities in ASDFDataSet are extremely well written.  Thanks for crafting such a useful package and example of good coding!

ASDF adoption is my long term goal, however, I'm temporarily tied to other data formats.  

Could anyone comment on whether the parallel processing methods in ASDFDataSet could be adapted to work on general obspy stream objects?  I'm not looking to speed up reading and writing traces to disk, only operations on obspy traces in memory such as instrument response removal, bandpassing, muting and so on.

Many thanks for any comments!

**Comment by krischer** [comment]
Hey Ryan,

thanks for the compliment. This fall I want to rewrite them to work in parallel on an arbitrary number of ASDF files at the same time.

To answer the rest of your questions: Its not really necessary to adapt `pyasdf` processing as it is fairly complex to achieve actual parallel I/O. Other file formats cannot really have that in the first place (or it would be a lot simpler like with SEG-Y). If you don't need parallel I/O it is really much much easier than what `pyasdf` is doing.

You can just any multiprocessing work queue - I like the implementation in `joblib` which is easy to use. But the default `multiprocessing.pool.Pool` in Python's stdlib is also pretty capable. If you don't even need a queue but can just split up your data before the fact you can use something like this (shameless self-advertisement): https://gist.github.com/krischer/2c7b95beed642248487a

I've been using this for a number of things and it works well. There are also some MPI based work queue implementations around but I cannot seem to find them right now.

Another point: You should benchmark this, but the slowest part of your whole processing chain is very likely just the calculation of the response - the rest is usually really fast - especially if downsample fairly close to nyquist before you do anything. This is because it calculates the response for every single frequency in the frequency domain. But the response really is fairly smooth so you could just calculate it for every n-th frequency bin and interpolate in-between - this should be a bunch faster. I've been meaning to add this to ObsPy for a while now but did not get around to it.

Cheers!

**Comment by rmodrak** [comment]
Nice explanation, thank you.  That's the answer I was hoping to hear.   

It wasn't obvious to me all the complexity of the class was a result of parallel IO.  If that's the case, then why not then decouple parallel signal processing from the parallel disk IO?  Is there a reason both are included together in the same method?

**Comment by krischer** [comment]
I have to give this a bit more thought but I don't really think this is possible. The actual processing (i.e. applying the function) is only very few lines.

The complexity comes (basically completely) from the I/O - especially the parallel writing. Each worker accumulates results until a certain memory threshold is reached; then it tells the master that it would like to write; once more then half or so of all workers would like to write the master tells every worker to pause processing after the next trace; then the meta-information about what each rank would like to write is scattered across all ranks and each rank writes the collective meta-information; then each rank can finally write its actual data and the loop continues until no more work needs to be done.

The data is already processed at the beginning of this chain so its really a non-issue.

**Comment by rmodrak** [comment]
P.S.  I am curious about decoupling the two because doing so might allow Wenjie's pypaw scripts to work on any obspy-supported data format, not just ASDF.  (Of course without ASDF there would be less efficient disk IO.)

**Comment by krischer** [comment]
> P.S. I am curious about decoupling the two because doing so might allow Wenjie's pypaw scripts to work on any obspy-supported data format, not just ASDF. (Of course without ASDF there would be less efficient disk IO.)

This is probably hard to do as ASDF is basically the only format that really stores all the required data in a single file - for all other formats you'd have to come up with some kind of custom structure I guess. But I'm open to discuss any generalizations and would be happy to help make them a reality if feasible.

**Comment by rmodrak** [comment]
Thanks for the helpful replies!

In the past I've tried to address the metadata issue through file format-depdendent plugins that return desired station information.  Sometimes all that's required for data processing is the station coordinates, in which case there's no need for a complicated custom structure.

I may try to refactor Wenjie's scripts as part of Carl Tape and other's newly funded software development proposal, so I appreciate your insights.
