### ISSUE TITLE
SUGGESTION: adding public APIs for parallel writing functions

### ISSUE THREAD

**Issue by icui** [SeismicData/pyasdf#67]
I've been using my own processing functions with pyasdf because process() and process_two_files() are not flexible enough for my needs. The methods I use for parallel writing include 
```
_add_trace_get_collective_information
_add_trace_write_collective_information
_add_trace_write_independent_information
```
```
_add_auxiliary_data_get_collective_information
_add_auxiliary_data_write_collective_information
_add_auxiliary_data_write_independent_information
```
While they work well, I felt that it's generally not a good thing to use the private methods of external libraries. So I was wondering if it is possible to add some simple wrappers to these functions just to make them accessible through public methods?

**Comment by krischer** [comment]
Hi @icui 

thanks for your thoughts on this. I understand the desire of yours to only use public API functions. In this case however I'd rather not add these to the public API because for me having them public means to commit to keeping them stable.

It is really quite hard to guarantee this in this particular case because HDF5 or MPI or something else might change something and then these have to be adapted - additionally I would consider them to be an implementation detail that most users should not call directly. You are an expert user so you are able to use them but you are also capable enough to adapt to any changes in case they might happen.

That being said I don't think they'll change anytime soon so you can keep using them.
